### PR TITLE
fix: prevent infinite loading issue on video browser

### LINKED ISSUE #397: Video browser stuck in loading v3
**Describe the bug**
Locally the video browser works but when deployed to a Sanity studio the loading spinner is stuck and videos are not displayed, this is for both choosing a video from a field and from the tabs at the top of the studio with the path /mux.

Videos will upload and display on the front end and can query data, but they dont show in the studio in the browser/select window.

Ive tried different API keys, signed URLs but nothing works.

**To Reproduce**
Install and deploy a clean sanity project e.g. https://github.com/sanity-io/sanity-template-nextjs-clean with mux plugin and deploy to a Sanity studio.

**Expected behavior**
Videos load

**Screenshots**
Screenshot 2024-12-20 at 22 42 54

**Which versions of Sanity are you using?**
@sanity/cli (global)          3.60.0 (latest: 3.68.3)
@sanity/assist                 3.0.8 (latest: 3.0.9)
@sanity/eslint-config-studio   4.0.0 (latest: 5.0.1)
@sanity/icons                  3.5.5 (up to date)
@sanity/vision                3.68.3 (up to date)
sanity                        3.68.3 (up to date)

**What operating system are you using?**

**Which versions of Node.js / npm are you running?**
10.1.0
v20.8.0

### PR DESCRIPTION
**Pull request by larixk**
This PR updates `useAssets.ts` by replacing the use of `createHookFromObservableFactory` with a memoized observable. This change addresses an incompatibility with recent versions of Sanity that caused infinite loading in the VideoBrowser, resulting in a broken user experience and potentially high costs due to the excessive number of requests made to Sanity. Fixes #397.

As this is my first contribution to this project—and to the Sanity ecosystem in general—I’d greatly appreciate a detailed review. I've based this code on the example in https://www.sanity.io/docs/studio-react-hooks#7a5503c777f4 but I’m open to any suggestions for improving this approach or aligning with standard practices for handling observables. Thank you for your time and feedback!

### CODE REVIEW

File: src/hooks/useAssets.ts [hunk 1]
```diff
@@ -14,33 +15,39 @@ export const ASSET_SORT_OPTIONS = {
...
 
 export default function useAssets() {
   const documentStore = useDocumentStore()
   const [sort, setSort] = useState<SortOption>('createdDesc')
   const [searchQuery, setSearchQuery] = useState('')
 
-  const [assetDocuments = [], isLoading] = useAssetDocuments({documentStore, sort, searchQuery})
+  const assetDocumentsObservable = useAssetDocuments({documentStore, sort, searchQuery})
+  const isLoading = assetDocumentsObservable === undefined
+  const assetDocuments = isLoading ? [] : assetDocumentsObservable
```
Comment (R-Delfino95) [inline src/hooks/useAssets.ts:50]: I tested it and everything seems to work as expected, including the browse feature in the structure section.

LGTM! One minor suggestion: could we move the `assetDocuments` definition inside the useMemo for `assets`? This way, we avoid recreating it unnecessarily across re-renders.

Comment (larixk) [reply src/hooks/useAssets.ts:50]: Thank you for the review and test. Unfortunately, I'm not sure how to implement your suggested change. 

The original code requires an `isLoading` boolean and an `assetDocuments` array. I decided to initialize the value of the assetDocumentsObservable to `undefined` and to compare its value with that that to determine `isLoading`. Moving this 'isLoading' logic into the useMemo where the observable is created is not an option, I think. Alternatively, using an empty array as the initial state would make it impossible for us to distinguish between a loading state and an 'empty result' state.

Note that the value of assetDocuments is only initialized to an empty array on line 50 if the assetDocumentObservable is loading, otherwise it uses the result of the observable, by reference. This should therefore not cause any unnecessary re-renders or performance issues.

**Comment by RitaDias** [comment]
Given that some time has passed since you opened this PR I just want to give a headsup that I'm currently looking into testing it and reviewing it :) 

(also, I apologise for the delay in the review)

File: src/hooks/useAssets.ts (hunk 1 above)
Comment (R-Delfino95) [reply src/hooks/useAssets.ts:50]: Thank you for your explanation! I see your point about distinguishing between the loading state and an empty result.
What I was suggesting is moving the `const assetDocuments` inside the `useMemo` so that it recalculates based on `isLoading` and `assetDocumentsObservable`. If we define it outside, there’s a chance that if `useAssetDocuments` returns `undefined` multiple times in a row, `assetDocuments` will be repeatedly set to an empty array. This could cause `useMemo` to unnecessarily recompute the array and trigger additional re-renders.

Let me know your thoughts!

Comment (RitaDias) [reply src/hooks/useAssets.ts:50]: I agree with @R-Delfino95 's points, it would be a nice change :)
Once we iron out this, I'd be ok with ✅ this PR!

Once more, thank you for setting up this PR!

Comment (larixk) [reply src/hooks/useAssets.ts]: Ah! I misunderstood which `useMemo` you were referring to. I thought you were suggesting adding it to the `useMemo` that's called on line 27, but I understand now that you were referring to the `useMemo` that came after my previous changes.

The suggested change has now been implemented and further simplified, as the only reason we initialized the empty array was to be able to pass it to `collate`. An inline nullish coalescing operator does the same.

Ready for another review!

**Review by RitaDias — APPROVED** [review]
Thank you for doing this 🙏 :shipit:

**Review by R-Delfino95 — APPROVED** [review]
Awesome! Thank you for these changes 😄

**Comment by larixk** [comment]
Thanks for reviewing! Looking forward to seeing this released. Any indication of what that process looks like from here?

**Comment by RitaDias** [comment]
> Thanks for reviewing! Looking forward to seeing this released. Any indication of what that process looks like from here?

I'll take it from here :heart: 
Merging it!
